config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
  end
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :posts do 
    resources :comments, only: [:create]
    collection { post :import }
  end
  resources :tags, only: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :description, presence: true, allow_blank: false
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_rich_text :description
  has_many :comments, dependent:  :destroy
  has_many :tags, dependent:  :destroy
  accepts_nested_attributes_for :tags, reject_if: :all_blank, allow_destroy: true
  paginates_per 3
  has_one_attached :thumbnail
  #has_one_attached :arquivo
  validates :thumbnail, attached: true, content_type: ['image/png', 'image/jpg', 'image/jpeg'],
                                     dimension: { width: { min: 500, max: 1920 },
                                                  height: { min: 600, max: 1080 }, message: 'is not given between dimension' }

  validates :title, length: {minimum: 5} 
  
  
  def optimized_image(image,x,y)
    
    return image.variant(resize_to_fill: [x, y]).processed if image.present?
  end

  
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :post

  validates :title, presence: true, length: {minimum: 3} 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments, dependent:  :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
    def create 
      @comment = @post.comments.new(comment_params)
      set_user()
      @comment.save
      redirect_to post_path(@post)
    end

    private 

    def comment_params
      params.require(:comment).permit(:description, :post_id )
    end

    def set_post 
      @post = Post.find(params[:post_id])
    end

    def set_user() 
      if current_user
        @comment.user = current_user
      else 
        user = User.find_by_email('anonymous@mail.com')
        user = User.create(email: 'anonymous@mail.com', password:'123456') if user.nil?
        @comment.user = user    
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :destroy, :update, :show]
  before_action :authenticate_user!, except: [:show]
  def index 
    @posts = Post.where(user: current_user)
    
    tag_titles = params[:tags]
    
    if tag_titles.present?
      @posts = @posts.joins(:tags).where(tags: { title: tag_titles }).distinct 
    end
  end

  def new  
    @post = Post.new
    @tags = @post.tags.build
  end

  def create
    @post = Post.create(post_params)
    @post.user = current_user
    if @post.save 
      redirect_to posts_path, notice: t('post was successfully created!')
    else
      render :new
    end
  end

  def edit 
    redirect_to posts_path, alert: t("you don't have permission to edit this") unless @post.user == current_user
  end

  def update 
    if @post.update(post_params)
      redirect_to posts_path, notice: t('post was successfully updated!')
    else
      render :edit 
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.order("created_at DESC")
  end

  def destroy 
    @post.destroy
    redirect_to posts_path, notice: t('post was successfully detroyed!')
  end

  def import
    
    @arquivo = params[:arquivo]
    response = check_extension(@arquivo)
    if response
      redirect_to posts_path, notice: t('post was successfully imported!')
    else
      redirect_to posts_path, notice: t('post was not successfully imported!')
    end
  end
  private 


  
  def post_params 
    params.require(:post).permit(:title, :description, :thumbnail,tags_attributes: [:id, :title])
  end

  
  def set_post 
    @post = Post.find(params[:id])
  end

  def check_extension(arquivo)
    extension = [".txt"]
    if extension.include?File.extname(arquivo) 
      File.open(arquivo) do |f|
        f.each_with_index do |linha, i|
        coluna = linha.split(",")
        title = "#{coluna[0]} - #{i}"
        user_id = coluna[1]
        response = HardWorker.perform_async(title, user_id)
        end
      end
      return response
    end
    false
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  
  def show
    @tag = Tag.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.order("created_at DESC").page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
       
    if level == "alert"
         "alert alert-warning alert-dismissible fade show"
    elsif level == "notice"     
         "alert alert-success alert-dismissible fade show"
    elsif level == "error" 
         "alert alert-danger alert-dismissible fade show"
    else
         "alert alert-primary alert-dismissible fade show"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioMaino</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
  </head>

  <body>
    <div class="container">
      <%= render "shared/navigation" %>
      
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>" role="alert">
              <%= value %>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_comment.html.erb
<div class="row mt-3">
  <ul class='media-list'>
    <% @comments.each do |comment| %> 
    <li class="media">
      <div class="media-body">
          <span class="text-muted pull-right">
            <small class="text-muted">
              <%= comment.created_at.strftime("Posted on %m/%d/%Y at: %I:%M%p") %>
            </small>
          </span>
          <strong class="text-success"><%= "@#{comment.user.email}" %></strong>
          <p>
          <%= comment.description%>
          </p>
          
        </div>
    </li>
    <hr>
    <br>
    <% end %> 
  </ul> 
</div>

app/views/posts/_form.html.erb
<% post.errors.each do |key, value| %>
<div class="<%= flash_class('error') %>" role="alert">
  <%= t("#{key}") %> <%= value %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

<%= form_with(model: post, local: true)  do |form| %>

<div class="form-group">
  <%= form.label :title %>
  <%= form.text_field :title , class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :thumbnail %>
  <%= form.file_field :thumbnail , class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :description %>
  <%= form.rich_text_area :description  %>
</div>


<br/>
<h4>Tags</h4>
<div id="tags">
    <%= form.fields_for :tags do |tag| %>
      <%= render 'tag_fields', f: tag %> 
    <% end %>

    <div class="links">
      <!-- COMENTÁRIO: O link_to_add_association é um helper provido pela gem -->
        <%= link_to_add_association 'add tags', form, :tags %>
      <br><br>
    </div>

</div>

<div class="mt-2">
  <%= form.submit 'Enviar', class: 'btn btn-primary' %>
</div>

<% end %>

<div class="pt-3">
  <%= link_to t('back'), posts_path %>
</div>

app/views/posts/_tag_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
 
  <!-- COMENTÁRIO:
    link_to_remove_association é o helper que o cocoon nos fornece para deletar algum nested
  -->
  <%= link_to_remove_association "remove tag", f %>
 
  <br><br><br>
</div>

app/views/posts/edit.html.erb
<section class="py-5">
  <h1>Edit post</h1>

  <%= render 'form', post: @post %>
</section>

app/views/posts/index.html.erb
<section class="py-3">
  <%= form_tag(posts_path, method: :get) do %>
  <div class="form-group mt-3 col-sm-10">
    Filtar por Tags: 
      <%= text_field_tag(:tags) %>
      <%= submit_tag("Search") %>
    <% end %>
  </div>
  
  <hr>
  <h2 class="mt-2 mb-3">Importar Posts</h2>
  <div class="row">
    <%= form_tag import_posts_path, multipart: true  do %>
      <%= file_field_tag :arquivo, required: true  %> <small id="emailHelp" class="form-text text-muted">Extensão permitida .txt</small>
      <%= submit_tag "Import" , class: 'btn btn-info' %>
    <% end %>
      
  </div>

  <br>
  
  <table class="table">
    <thead>
      <tr>
        <th>Id</th>
        <th><%= t("title") %></th>
        <th><%= t('owner') %></th> </th>
        <th colspan="3"> <%= link_to "#{t('new')} Post", new_post_path, class: 'btn btn-success' %></th> 
        <th ><%= t('tags') %></th> 
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td> <%= post.title %> </td>
        <td> <%= post.user.email %></td>
        
        <td > <%= link_to t('edit'), edit_post_path(post), class: 'btn btn-warning' %></td>
        <td >
          <%= link_to t('show'), post_path(post), class: 'btn btn-info'  %>
        </td>
        <td >
          <%= link_to t('delete'), post_path(post), method: :delete, data: { confirm: 'Você está certo disso ?' }, class: 'btn btn-danger'  %>
        </td>
        <td>
          <% post.tags.each do |tag| %>
           <span class="tag"><%= tag.title %></span> 
          <% end %>
        </td>
        
      </tr>
      <% end %>
    </tbody>
  </table>
  
  
</section>

app/views/posts/new.html.erb
<section class="py-5">
  <h1><%= t('new') %> post</h1>

  <%= render 'form', post: @post %>
</section>

app/views/posts/show.html.erb
<div style="width: 100%; height:300px; overflow-y: hidden">
  <% if @post.thumbnail %>
  <img class="card-img-top" 
              src="<%= url_for @post.optimized_image(@post.thumbnail, 586, 180) %>" 
              alt="Blog Post Image Card" 
              />
  <% end %>
</div>
<div class="container" style="margin-top: 2em">
  <div class="row">
    <div class="jumbotron" style="width: 100%; background-color:ivory">
      <h1 class="display-4">
        <%=  @post.title %>
      </h1>
      <p class="lead">
        <%= @post.updated_at.strftime("%d/%m/%Y %H:%M:%S") %> <%= t('by') %> <%= @post.user.email %>
      </p>
      <hr class="my-4" />
      <div class="post_body">
        <%= @post.description %>
      </div>
    </div>
    <div class='row'>
      <p class='col-3'><strong>Add Comment </strong>:</p> 
      <div class="col-12">
        <%= form_with model: [@post, @comment], local: true do |f| %>
          <div class="form-group">
            <%= f.text_area :description, rows: 3, class: 'form-control'%>
              <%= f.submit "Comment", class: 'btn btn-dark mt-3 ' %>
          </div>
          
        <% end %>
    
      </div>
    </div>
    <%= render "posts/comment" %>
    
    <h4>Tags</h4>
    <% @post.tags.each do |tag| %>
      <%= link_to (tag.title), tag_path(tag) %>
    <% end %>
  </div>
  <br>  <br>
  <%= link_to t('back'),  posts_path, class: 'btn btn-secondary col-2'  %>
  
</div>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Blog Mainô</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <% if current_user %>
                <li class="nav-item">
                        <%= link_to t('My Posts'), posts_path, class: "dropdown-item" %>     
                </li>
                <% end %>
                
            </ul>
            <% if current_user %> 
                <ul class="navbar-nav">
                    
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> 
                            
                            <%= current_user.email %> 
                        
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            
                            <li>
                                <%= link_to t('edit'),edit_user_registration_path(current_user), class: "dropdown-item" %>
                            </li>
                            <li><hr class="dropdown-divider" /></li>
                            <li>
                                <%= link_to t('logout'),destroy_user_session_path,method: :delete, class: "dropdown-item" %>
                            </li>
                    </li>
                </ul>
                <% else %>
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <%= link_to 'Login', new_user_session_path, class: "dropdown-item" %>
                    </li>
                </ul>
            <% end %>
        </div>
    </div>
</nav>

app/views/tags/show.html.erb
<div class="container" style="margin-top: 2em">
  <div class="row">
    <div class="jumbotron" style="width: 100%; background-color:ivory">
      <h1 class="display-4">
        <%=  @tag.title %>
      </h1>
      <p class="lead">
        <%= @tag.updated_at.strftime("%d/%m/%Y %H:%M:%S") %> <%= t('by') %> <%= @tag.post.user.email %>
      </p>
      <div class="post_body">
        <h3><%= @tag.post.description %></h3>
      </div>
    </div>
  </div>

app/views/welcome/index.html.erb
<div class="container">


  <% if @posts.count() > 0%>
  <% @posts.each do |post| %>
          <div class="row">
            <div class="card mb-3">
              <% if post.thumbnail %>
              <img class="card-img-top" 
              src="<%= url_for post.optimized_image(post.thumbnail, 586, 180) %>" 
              alt="Blog Post Image Card" 
              />
              <% end %>
              <div class="card-body">
                <h5 class="card-title">
                  <%= link_to post.title,post %>
                </h5>
                <p class="card-text">
                  <%= post.description.to_plain_text.truncate_words(100) %>
                </p>
                <p class="card-text">
                  <small class="text-muted">
                    <%= post.updated_at.strftime("%d/%m/%Y %H:%M:%S") %> by <%= post.user.email %> | <%= post.comments.count %>
                  </small>
                </p>
              </div>
            </div>
          </div>
        
          
  <% end %>
  <div class="mt-3 pagination pull-right">
  <%= paginate @posts %>
  </div>
  <% else %>
    <div class="text-align center">No posts yet.</div>
  <% end %>

  
</div>